#!/bin/sh

# Xcode Cloud checks out the repository without Underveis.xcodeproj — it is
# generated by XcodeGen and git-ignored (see project.yml / CLAUDE.md). Install
# XcodeGen and generate the project so the build step can find it.

set -e

brew install xcodegen
cd "$CI_PRIMARY_REPOSITORY_PATH"
xcodegen generate
